<article>
	<h2>Snake</h2>
	<section class="sf wrapper">
		<canvas class="sf box" id="gameWindow" onload=""></canvas>
		<div class="sf box size-3">Difficulty:</div>
		<select class="sf box size-3" id="difficulty">
			<option>Easy</option>
			<option>Medium</option>
			<option>Hard</option>
			<option>Hardcore</option>
		</select>
		<input type="button" value="New Game" class="sf box button size-4" onclick="startGame();this.blur();"/>
	</section>
	
</article>