<article>
	<h1>Upload Files</h1>
	<script>
	function showFileList() {
		var fileInput = document.getElementById('FileInput');
		var fileList = document.getElementById('FileList');
		fileList.innerHTML = '';
		for (var i in fileInput.files) {
			var file = fileInput.files[i];
			if (typeof file !== 'object') { continue; }
			var name = file.name;
			var ext = getExtension(name)
			var div = document.createElement('div');
			div.className = "sf box lh32";
			var img = document.createElement('img');
			img.className = "sf hw32";
			img.src = getIconSrc(ext);
			div.appendChild(img);
			div.innerHTML += name;
			fileList.appendChild(div);
		}
	}
	function clearFileList() {
		document.getElementById('FileUpload').reset();
		document.getElementById('FileInput').onchange();
	}
	function getExtension(filename) {
		return filename.split('.').pop().toLowerCase();
	}
	function getIconSrc(ext) {
		if (ext === 'jpeg') { ext = 'jpg'; }
		return '/css/img/ext_' + ext + '_32x32.png';
	}
	</script>
	<form action="/media/upload/" method="post" enctype="multipart/form-data" target="UploadFrame" id="FileUpload" class="sf wrapper dark round">
		<input type="hidden" name="<?php echo ini_get("session.upload_progress.name"); ?>" value="media">
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" />
		<input id="FileInput" type="file" name="files[]" multiple class="sf hide" onchange="showFileList()" accept=".png,.gif,.jpg,.jpeg,.mp3,.mp4,.pdf,.zip">
		
		<div class="sf wrapper">
			<p class="sf box lh32">Allowed files:
				<img alt="png" src="/css/img/ext_png_32x32.png" class="sf hw32">
				<img alt="gif" src="/css/img/ext_gif_32x32.png" class="sf hw32">
				<img alt="jpg" src="/css/img/ext_jpg_32x32.png" class="sf hw32">
				
				<img alt="mp3" src="/css/img/ext_mp3_32x32.png" class="sf hw32">
				
				<img alt="mp4" src="/css/img/ext_mp4_32x32.png" class="sf hw32">
				
				<img alt="pdf" src="/css/img/ext_pdf_32x32.png" class="sf hw32">
				
				<img alt="zip" src="/css/img/ext_zip_32x32.png" class="sf hw32">
			</p>
		</div>
		
		<div class="sf wrapper">
			<input type="button" class="sf box button size-5 start" value="Select Files" onclick="$('#FileInput').click();">
			<input type="submit" class="sf box button size-5 end" value="Upload">
		</div>
		
		<div id="FileList" class="sf wrapper">
		</div>
	</form>
</article>
<article>
	<h1>Progress</h1>
	<iframe id="UploadFrame" name="UploadFrame" class="sf box" onload="clearFileList()">
	</iframe>
</article>